### ISSUE TITLE
[Critical] Missing DLL

### ISSUE THREAD

**Issue by knight-ryu12** [zoogie/TADpole#1]
ctr-dsiwaretools need libcrypto, due to missing DLL, ctcert handling is not working

**Comment by zoogie** [comment]
Is this the same dll as what seedminer.exe was missing?

**Comment by knight-ryu12** [comment]
Yes

2018/02/04 午前5:11 "zoogie" <notifications@github.com>:

**Comment by jason0597** [comment]
yeah i get missing DLL as well
had to download libcrypto-1_1-x64.dll from some random dll website and put it in the resources folder, then it worked fine

**Comment by georgesofianosgr** [comment]
On Windows 10 64bit I have an error of missing zlib1__.dll , tried downloading and placing zlib but now crt_dsiwaretool crashes :(

**Comment by zoogie** [comment]
I'll add it to the release archive in a bit.

**Comment by zoogie** [comment]
Should be fixed now.

**Comment by georgesofianosgr** [comment]
Yes, it's ok now :)
