### ISSUE TITLE
Issue upon finalization - Missing zlib1__.dll

### ISSUE THREAD

**Issue by gtsatsis** [zoogie/TADpole#2]
Hey,

It seems that I am "missing" zlib1.dll, even though I have it. I also have renamed it to contain the two underscores and they make the program start incorrectly, is there a certain version I should be using?

**Comment by zoogie** [comment]
I just had someone from gbatemp run into this
https://gbatemp.net/threads/seedminer-single-system-dsiware-injection.495685/page-3#post-7818886
Try that dll.

**Comment by gtsatsis** [comment]
It worked! Thanks!

**Comment by gtsatsis** [comment]
Hmm, after loading it up, it seems to be still booting up the original game, (Faceez: Monsters) - Would you mind telling me the exact commands I should type in to do it?

( the order I used was dump and then rebuild )

**Comment by zoogie** [comment]
rename the sudoku.nds file to srl.nds.inject and rename the sudokuhax save to public.sav.inject and place both in the 4B464D45 folder.

The commands were correct you just forgot to add the injected files I think.

**Comment by gtsatsis** [comment]
Doing that results in the game being replaced by Sudoku, but Sudoku launches normally, any steps I should do from Sudoku?

**Comment by zoogie** [comment]
Did you go past the menu? That's when hax triggers.

**Comment by gtsatsis** [comment]
Yep, I am currently in a round of Sudoku - Fully functional game, Just to verify, THIS is the one you meant to download and inject, right? https://i.imgur.com/EZXZj1K.png

**Comment by zoogie** [comment]
Oh, I forgot that plailect does the fat injection with savedata.bin. You need to take the pre-injected public.sav and use that. 

https://gbatemp.net/threads/release-twltool-dsi-downgrading-save-injection-etc-multitool.393488/
You can find one in the attachment. I think the US public.sav works with europe.

**Comment by gtsatsis** [comment]
@zoogie The top screen goes green, the bottom screen says Touch to Start but then nothing happens, control is still available (Home button)

**Comment by zoogie** [comment]
Give me a bit and I'll make you a save.

**Comment by zoogie** [comment]
There you go.
[public.zip](https://github.com/zoogie/TADpole/files/1692597/public.zip)

**Comment by gtsatsis** [comment]
It worked! I just now need to find where to put the 2.54-0_11.4_OLD.firm file! (I guess trial and error will be my friend)

**Comment by gtsatsis** [comment]
Works just fine! Following the rest of 3ds.guide, seems like it's all working!

Issue closed!
