### ISSUE TITLE
TADpole.exe Triggering Virus Detection from Windows Defender 

### ISSUE THREAD

**Issue by GhostSonic21** [zoogie/TADpole#3]
Basically a mirror of https://github.com/zoogie/seedminer/issues/7, but for TADpole. TADpole.exe is being detected as "Trojan:Win32/Tiggre!plock" by Windows Defender, possibly other virus scanners.

Screenshot:

![image](https://user-images.githubusercontent.com/8278613/35900543-57d008c6-0b87-11e8-86fa-1baa29edac3e.png)

**Comment by zoogie** [comment]
All I did was compile seedminer_launcher.py and tadpole.py with pyinstaller. :/

This is what I get for trying to make things easy for people, lol.

**Comment by GhostSonic21** [comment]
https://github.com/pyinstaller/pyinstaller/issues/3157 Seems like a pyinstaller problem. They're just directing users to report to anti-virus vendors. Probably won't work in this case though, it's more likely to cause paranoia on GBATemp.

**Comment by zoogie** [comment]
At least I'm being transparent about it. We'll see.
https://gbatemp.net/threads/seedminer-single-system-dsiware-injection.495685/page-19#post-7823406

**Comment by zoogie** [comment]
The solution to this issue, for anyone who is concerned about viruses, is to run the functionally equivalent .py script.
