### ISSUE TITLE
"libcrypto-1_1-x64.dll was not found"

### ISSUE THREAD

**Issue by Koruudo** [zoogie/TADpole#4]
I am attempting to launch the TADpole.py with "rebuild", but once it hands the process to the dsiwaretool, it keeps throwing an error that "libcrypto-1_1-x64.dll" is missing. I installed both versions of 64-bit OpenSSl, and even tried putting the dll in TADpole/resources, but I can't get past this error. Could you please provide details and maybe put OpenSSL in the requirements list for this? Thanks.

Contact me @ setherz6104@gmail.com

**Comment by jason0597** [comment]
put 2 underscores at the end of the filename (before the extension)

**Comment by zoogie** [comment]
Should be fixed.
