### ISSUE TITLE
dsiware injection stuff

### ISSUE THREAD

**Issue by YYoshi241** [zoogie/TADpole#6]
I followed the seedminer instructions and got to the part on using TADpole. The problem is that I don't know where to download the appropriate srl.nds.inject and public.sav.inject for my game. (Also this website needs instructions relating to this, maybe. Sorry I'm new to this).

**Comment by YYoshi241** [comment]
mario vs. donkey kong minis march again usa

**Comment by GhostSonic21** [comment]
Though the documentation is a fair bit vague, this isn't exactly an issue with the software.

But for the sake of answering the question, the appropriate files can be found on 3ds.guide page linked on the bottom of seedminer's readme. I believe the relevant file is listed under "sudokuhax injection .zip corresponding to your region". If I'm correct, the .app file should be the file you want to rename to "srl.nds.inject", and likewise with the .sav file to "public.sav.inject".

**Comment by zoogie** [comment]
Any saves you need for injection can be found here
https://github.com/zoogie/3ds_dsiwarehax_installer/releases/tag/v1.2
The .app files that you rename to srl.nds.inject can be found at 3ds.guide
The save files in 3ds.guide are broken down to be injected into fat archives with a tool like godmode9. this make them rather difficult to use with tadpole, being that it operates PC-side. The public.sav's in that above link are pre-injected .sav archives.

I'll eventually add that this info to the documentation.

**Comment by latiosu** [comment]
@zoogie I'm happy to provide an update to the repo's README.md to reflect this

**Comment by YYoshi241** [comment]
I found the files already... I posted a TADpole ready zip of these on my page @YYoshi241

**Comment by latiosu** [comment]
@YYoshi241 This is awesome, I'll upload my PR to link to these files. Thanks Yoshi!
